version: "3.8"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres_dev
    environment:
      POSTGRES_USER: fer
      POSTGRES_PASSWORD: pwc
      POSTGRES_DB: dechallenge
    ports:
      - "12345:5432"

  typesense:
    image: typesense/typesense:28.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Web UI Port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./minio-data:/data
    command: minio server /data --console-address ":9001"
