version: "3.8"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres_dev
    environment:
      POSTGRES_USER: fer
      POSTGRES_PASSWORD: pwc
      POSTGRES_DB: dechallenge
    ports:
      - "12345:5432"

  typesense:
    build:
      context: .
      dockerfile: Dockerfile.typesense
    container_name: typesense_dev
    environment:
      TYPESENSE_API_KEY: my_secure_api_key
      TYPESENSE_DATA_DIR: /data
    ports:
      - "8108:8108"
