version: "3.8"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres_dev
    environment:
      POSTGRES_USER: fer
      POSTGRES_PASSWORD: pwc
      POSTGRES_DB: dechallenge
    ports:
      - "12345:5432"

  typesense:
    image: typesense/typesense:28.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'