version: "3.8"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres_dev
    environment:
      POSTGRES_USER: fer
      POSTGRES_PASSWORD: pwc
      POSTGRES_DB: dechallenge
    ports:
      - "12345:5432"

  typesense:
    image: typesense/typesense:28.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./minio-data:/data
    healthcheck:
      test: [ "CMD", "mc", "alias", "set", "myminio", "http://minio:9000", "admin", "password" ]
      interval: 5s
      retries: 5

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " sleep 5; mc alias set myminio http://minio:9000 admin password; (mc ls myminio/raw || mc mb myminio/raw); (mc ls myminio/processed || mc mb myminio/processed); exit 0; "
