"""Add gold tables

Revision ID: 3497c30b2fd6
Revises: 6325b95e1064
Create Date: 2025-03-05 10:40:28.015184

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3497c30b2fd6"
down_revision: Union[str, None] = "6325b95e1064"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gold_album_performance",
        sa.Column("album_name", sa.String(), nullable=False),
        sa.Column("total_songs", sa.Integer(), nullable=True),
        sa.Column("avg_duration", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("album_name"),
    )
    op.create_table(
        "gold_artist_performance",
        sa.Column("artist_name", sa.String(), nullable=False),
        sa.Column("total_songs", sa.Integer(), nullable=True),
        sa.Column("avg_tempo", sa.Float(), nullable=True),
        sa.Column("avg_loudness", sa.Float(), nullable=True),
        sa.Column("total_duration", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("artist_name"),
    )
    op.create_table(
        "gold_song_details",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("artist_name", sa.String(), nullable=True),
        sa.Column("artist_location", sa.String(), nullable=True),
        sa.Column("album_name", sa.String(), nullable=True),
        sa.Column("tempo", sa.Float(), nullable=True),
        sa.Column("key", sa.Integer(), nullable=True),
        sa.Column("loudness", sa.Float(), nullable=True),
        sa.Column("mode", sa.Integer(), nullable=True),
        sa.Column("time_signature", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("lyrics", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("title"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gold_song_details")
    op.drop_table("gold_artist_performance")
    op.drop_table("gold_album_performance")
    # ### end Alembic commands ###
