"""Add new table

Revision ID: 517306f2c17b
Revises: fd45d6051557
Create Date: 2025-03-03 13:10:11.527678

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "517306f2c17b"
down_revision: Union[str, None] = "fd45d6051557"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_features",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tempo", sa.Float(), nullable=True),
        sa.Column("key", sa.Integer(), nullable=True),
        sa.Column("loudness", sa.Float(), nullable=True),
        sa.Column("mode", sa.Integer(), nullable=True),
        sa.Column("time_signature", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("artists", sa.Column("location", sa.String(), nullable=True))
    op.drop_column("artists", "country")
    op.add_column("songs", sa.Column("lyrics", sa.String(), nullable=True))
    op.add_column("songs", sa.Column("audio_feature_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "songs", "audio_features", ["audio_feature_id"], ["id"])
    op.drop_column("songs", "play_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "songs",
        sa.Column("play_count", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "songs", type_="foreignkey")
    op.drop_column("songs", "audio_feature_id")
    op.drop_column("songs", "lyrics")
    op.add_column(
        "artists",
        sa.Column("country", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("artists", "location")
    op.drop_table("audio_features")
    # ### end Alembic commands ###
